// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Torchbearer.Models;

namespace Torchbearer.Migrations
{
    [DbContext(typeof(UnionLarpContext))]
    [Migration("20181103155408_SuggestedHelp")]
    partial class SuggestedHelp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Torchbearer.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("BeginnersLuckHealth");

                    b.Property<string>("Name");

                    b.Property<string>("QuickDescription");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Torchbearer.Models.SuggestedHelp", b =>
                {
                    b.Property<int>("SkillId");

                    b.Property<int>("SuggestedHelpSkillId");

                    b.HasKey("SkillId", "SuggestedHelpSkillId");

                    b.ToTable("SuggestedHelp");
                });
#pragma warning restore 612, 618
        }
    }
}
